In [1]:
pip install -r requirements.txt

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'


In [2]:
# 아 여긴 깔려있나

In [3]:
import pandas as pd
import numpy as np

# 라이브러리 설치 방법
- 구글 코랩이나 주피터에서 잠깐 쓰고 싶을 때
- !pip install numpy
- 이런 식으로 쓰면 됨

In [5]:
# help(클래스) : help(np) -> 설명나옴

In [6]:
print(np.__version__)

2.1.1


In [7]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]
num1 + num2

[1, 2, 3, 4, 5, 6]

In [8]:
# 이게 아니라 더해달라고 !
# gpt 한테 물어보면 반복문 쓰라함. 이러면 시간 오래걸림. 그래서 np 씀

In [10]:
num1_arr=np.array(num1)
num2_arr=np.array(num2)

num1_arr+num2_arr

array([5, 7, 9])

## 메서드, 속성 활용하기 (공식문서 보고)
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
- 속성: 지금 가진 데이터 현재 상태 확인하기 위함.
- 메서드: 먼가 액션을 하고 싶을 때

In [ ]:
# 타입 메서드 사용해서 타입 확인 !
print(type(num1_arr))
# 클래스에는 속성과 메서드가 있다. 공식문서를 봐보자

### 속성

In [16]:
# 공식문서를 보고 Attribute(속성) 확인해보자
num1_arr.T

array([1, 2, 3])

In [21]:
num1_arr.dtype # 데이터 타입 표현

dtype('int64')

In [18]:
num1_arr.shape # 1차원, 값이 3개이다.

(3,)

In [19]:
num1_arr.ndim # 차원 확인

1

### 메서드
- 쓸려고 봤는데 documentation 불친절 하면, 챗지피티에게 sample code 달라고 물어봐

In [23]:
num1_arr.max() # 64 준건 가장 큰 공간 주겠따. 그러면 메모리 비용 발생함. 내가 다룰 데이터 크기에 따라 데이터 타입 바꿔도 됨.ㅌ

np.int64(3)

In [24]:
# type 바꾸기
num1_arr = np.array(num1, dtype="int8")
num1_arr.dtype

dtype('int8')

# numpy
## numpy 배열을 만들어보자

In [25]:
# 기본적으로 다른 데이터 자료형으로 numpy 배열로 변환
# 1 배열 생성 해보자
print(np.ones(3))

[1. 1. 1.]


In [26]:
# ones: 1열의 배열로 뽑겠다

In [27]:
print(np.zeros(5)) # zeros : 0을 출력함

[0. 0. 0. 0. 0.]


In [28]:
# 1차원, 2차원, 3차원, 4차원 ... 배열 생성 가능!
print(np.ndarray(shape=(2,2,2), dtype=float, order='F'))

[[[0.0000e+000 0.0000e+000]
  [0.0000e+000 0.0000e+000]]

 [[0.0000e+000 1.3715e-320]
  [0.0000e+000 0.0000e+000]]]


In [29]:
arr = np.ndarray(shape=(2,2,2), dtype=float, order='F')
arr.shape

(2, 2, 2)

## 배열의 차원을 변경해보자

In [31]:
temp_arr = np.arange(16)
temp_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
# 1 차원 배열에 16개 값을 준 것

In [33]:
# 이 배열의 값을 2, 3 차원으로 변경해보자
# 이럴 때 사용하는 메서드 -> 공식문서 검색 -> 
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html

In [34]:
temp_arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
temp_arr.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [36]:
temp_arr.reshape(1,2,8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]])

In [37]:
temp_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
temp_arr_1 = temp_arr.reshape(1,2,8)
temp_arr_1.ndim

3

In [39]:
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333], dtype = np.float32)

print(a16)
print(a32)

[1.333]
[1.333333]


In [ ]:
# 보면 두개다 입력값은 같은데, np 배열로 변환할 때 비트 단위를 다르게 줌. 
# 그러니까 나오는 값이 다름 -> 다른 숫자가 됨

In [40]:
arr = np.array([-1, 2, -3])
arr/0

C:\Users\chaer\AppData\Local\Temp\ipykernel_3764\3465403327.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

In [41]:
# 메서드를 사용하다 보면, 어쩌다보면 0으로 나눈 경우 나올 수도 있음
# ([-inf,  inf, -inf]) <- 이런 에러 나오면
# 내가 다루는 배열 안에 0으로 나눈게 있ㄴㅏ??? 의심해봐야 함

## 결측치
- Missing Values : 잃어버린 값
- nan : Not a Number, ==> 아직 정의되지 않은 숫자 의미

In [42]:
print(np.nan, type(np.nan))

nan <class 'float'>


In [46]:
# type 은 float 임. 문법임

In [44]:
# inf : 양의 무한대, -inf: 음의 무한대

In [45]:
print(np.inf, type(np.inf))

inf <class 'float'>


In [47]:
print(-np.inf, type(-np.inf))

-inf <class 'float'>


In [48]:
# float 임 . 문법임

In [49]:
arr=np.array([-1, -2, -3])
print(arr+np.nan)
print(arr+np.inf)

[nan nan nan]
[inf inf inf]


In [50]:
# 저렇게 결과가 나오면: 배열 안에 결측치나 무한대가 있구나. 하고 생각해야함!
# 이건 에러가 아님. 주어진 대로 연산한 거임.
# 문제는: 행렬에서 뭔가 무한대나, 결측치가 있어서 저렇게 연산된 것임

## 넘파이 인덱싱 & 슬라이싱 

In [52]:
arr = np. arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [55]:
arr = np.arange(10).reshape(2,5)
arr[0][1]

np.int64(1)

In [59]:
arr = np.arange(10000).reshape(100, 100)
arr[0:4][0:1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [60]:
arr = np.arange(4)
arr[:2]

array([0, 1])

In [61]:
np.arange(4)

array([0, 1, 2, 3])

In [73]:
# 문제
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
arr[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
arr[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
arr[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# arr[행, 열]
# 

In [83]:
arr[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
arr[1:4] # 4를 입력해야 함!!!!!!!!!!!!1

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
arr[1:4 , 2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [87]:
arr[1:, 2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [89]:
arr[:,:] # 전체 데이터 출력

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Broadcasting 연산
- https://numpy.org/doc/stable/user/basics.broadcasting.html
- 딥러닝 하면 필연적으로 데이터의 행과 열이 다름.
- 

In [90]:
a = np.array([1,2,3])
b = np.array([1,2,3])
a+b

array([2, 4, 6])

In [91]:
a = np.array([1,2,3])
b = 3.0
a+b

array([4., 5., 6.])

In [92]:
# 두 방식 모두 연산이 됨

In [93]:
a = np.array([1,  2,   3])
#             3.0 3.0  3.0
b = 3.0
a+b
# b에 값을 하나만 입력했지만 알아서 연동해, 일차원 배열 만들어 연산한 것
# 배열이 달라도 브로드캐스팅 룰에 따라 연산을 해준다 -> 브로드캐스팅 연산
# 이와 관련된 주요한 내용들은 numpy documentation 보면 설명이 잘 되어 있음
# np에서 수치연산 할 떄, 차원이 달라도 연산 할 수 있다.

array([4., 5., 6.])

### 문제 1. 
문제: 모든 값이 0으로 2차원 배열 (5, 5) 만드세요. 

In [96]:
arr = np.zeros(25)
arr.reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
# 다른 방식
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 문제 2. 
임의의 3x3 크기의 배열을 생성하고 배열의 shape(모양), dtype(데이터 타입), 그리고 배열의 차원 수(ndim)를 출력하세요.

In [104]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
print(arr.shape, arr.dtype, arr.ndim)

(3, 3) int64 2


### 문제 3. 
- 주어진 배열에서 아래와 같이 슬라이싱 하세요. 
```
array([[ 5,  6],
       [ 9, 10]])
```

In [101]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
arr[1:3 , 1:3]

array([[ 5,  6],
       [ 9, 10]])

## 조건 연산
- 원하는 결괏값: True/False

In [106]:
arr = np.array([10, 20, 30])
arr > 10

array([False,  True,  True])

In [107]:
# 이 컨셉 굉장히 중요. pandas dataframe 할 때도 이 원리를 적용함

In [109]:
arr = np.array([10, 20, 30])
cond = [False, True, True] # 조건

arr[cond]

array([20, 30])

In [111]:
# 매우 중요!!
# 10보다 큰걸 가져오세요 -> true 값만 뽑은 걸 가져온 것

In [112]:
arr = np.array([18, 20, 50, 30, 16])
cond = arr > 18 # 조건

arr[cond]

array([20, 50, 30])

In [113]:
arr = np.array([18, 20, 50, 30, 16])
arr[arr > 18]

array([20, 50, 30])

In [119]:
arr = np.array([18, 20, 50, 30, 16, 65, 70])
# 다중 조건
con0 = arr > 18
con1 = arr < 65
# 두 가지 조건을 동시에 만족하는 애를 가져오고 싶다
arr[con0 & con1] # and 연산

array([20, 50, 30])

In [120]:
# or 연산 : |
arr[ con0 | con1  ]

array([18, 20, 50, 30, 16, 65, 70])

In [ ]:
# 권장사항, 이유: 판다스 다중조건 필터링 할 때는 아래 방법으로만 가능
# () 반드시 필요
arr[(con0 | con1)]

## np.where
- https://numpy.org/doc/stable/reference/generated/numpy.where.html
- 공식문서 확인해보세요



In [121]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
# 조건문임 
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

## 함수와 메서드

In [125]:
arr = np.arange(8).reshape(4,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [127]:
arr.sum() # arr 요소를 다 합한 값이 나옴

np.int64(28)

In [132]:
arr.sum(axis = None)

np.int64(28)

In [130]:
arr.sum(axis = 0) # x축 방향으로 데이터 합 구함

array([12, 16])

In [131]:
arr.sum(axis = 1) # y축 방향으로 데이터 합 구함

array([ 1,  5,  9, 13])

In [ ]:
# numpy 보단 dataframe 많이 씀. 거기에도 이런 거 있음

In [133]:
# 무작위 랜덤 함수 만들기
np.random.randint(10)

3

In [135]:
np.random.seed(42) # 이러면 랜덤 수 안바뀜. 나중에 머신러닝 할 때 이 코드 자주 사용함
np.random.randint(10)

6

In [137]:
np.random.randint(46, size = 6)
# 46dl dmlalgksms rjtdms 0~45번째 까지의 숫자 중 무작위로 가져오겠음

array([18, 22, 10, 10, 23, 35], dtype=int32)

In [138]:
# 배열로도 출력 가능
np.random.randint(46, size = (3, 4))

array([[39, 23,  2, 21],
       [ 1, 23, 43, 29],
       [37,  1, 20, 32]], dtype=int32)

In [139]:
x = np.linspace(0, 100 ,11) # 범위 주고, 균등하게 11개로 분할해라
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


# pandas

## pandas series

In [140]:
pd.__version__

'2.2.3'

In [141]:
data = [10, 20, 30]
s = pd.Series(data)
s

0    10
1    20
2    30
dtype: int64

In [142]:
print(type(s))

<class 'pandas.core.series.Series'>


In [ ]:
# 클래스 명이 길다. pandas.core.series.Series

### pandas documentation (공식 문서)
- https://pandas.pydata.org/
- 굉장히 빠르게 업데이트 되니, 자주 들어가게 될 것
- deprecations: 지원 중단되는 기능들
- API refrence 도 자주 감

In [143]:
data = np.arange(5)
s = pd.Series(data)
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [146]:
# Series 말고 Dataframe이라는 클래스 적용해보자
data = np.arange(5)
s = pd.DataFrame(data)
s

0
0  0
1  1
2  2
3  3
4  4

In [147]:
# 문자로도 해보자

In [149]:
data = ["시가", "고가"]
s = pd.Series(data)
s

0    시가
1    고가
dtype: object

In [150]:
data = ["시가", "고가"]
s = pd.DataFrame(data)
s

0
0  시가
1  고가

In [151]:
data = [8000, "9000"]
s = pd.Series(data)
s

0    8000
1    9000
dtype: object

In [153]:
# dtype: object
# 이게 머징
# object란 : int ,float, bool, datetime, category로 들어가기 그런, 형식이 정해지지 않은 상태 (흔히 문자열 이라 한다.) -> 변경(처리) 필요

## Series Index

In [156]:
data = [1000, 2000, 3000]
s = pd.Series(data)
s

0    1000
1    2000
2    3000
dtype: int64

In [157]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [159]:
print(s.index) # s.index의 클래스명. 하나의 객체다. -> RangeIndex도 들어가면 속성과 메서드 있을 것.

RangeIndex(start=0, stop=3, step=1)


In [160]:
# RangeIndex : s.index의 클래스명. 하나의 객체다. -> RangeIndex도 들어가면 속성과 메서드 있을 것.

In [161]:
# 저게 아니라 리스트 형태로 만들고 싶다

In [162]:
# sol1/ 형 변환
list(s.index)

[0, 1, 2]

In [163]:
# sol2/ 내부에서 처리
s.index.to_list()

[0, 1, 2]

In [165]:
# 클래스에는 항상 속성과 메서드가 있다. 메서드를 찾아 내부에서 처리 할 수 있다. 그게 sol 2. 
# 메서드 어케 찾냐? 공식 문서 확인 ! 
# 상속 받아서 쓰는 거일 수도 있으니, RangeIndex 보다 상위 클래스도 확인 해야함. 이를테면 Series
# Series 들어가서 list 검색하면 나옴 (.to_list)

## Series 생성하면서 Index도 같이 생성

In [167]:
data =[1000, 2000, 3000]
index = ["A","B","C"]

s=pd.Series(data, index)
s

A    1000
B    2000
C    3000
dtype: int64

In [168]:
data =[1000, 2000, 3000]
index = ["A","B","C"]

s=pd.Series(data=data, index=index)
s

A    1000
B    2000
C    3000
dtype: int64

In [169]:
#??

### .values

In [170]:
s. values

array([1000, 2000, 3000])

In [171]:
print(type(s.values))

<class 'numpy.ndarray'>


In [172]:
# type 확인해보면 numpy 배열이다.

## Series - Indexing (iloc, loc)

In [174]:
s

A    1000
B    2000
C    3000
dtype: int64

In [173]:
print(s.iloc[0])

1000


In [175]:
print(s.iloc[1])

2000


In [176]:
print(s.loc[0])

KeyError: 0

In [177]:
# KeyError: 0

In [178]:
print(s.loc["A"])

1000


In [182]:
data =[1000, 2000, 3000]
# index가 없음

s2=pd.Series(data=data)
print(s2.iloc[0])  # iloc에서의 0은 위치 0을 의미
print(s2.loc["A"]) # loc에서의 0dms fkqpf -을 의미

1000


KeyError: 'A'

In [181]:
# 차이점은 s2에는 인덱스가 없음. 
# iloc loc 차이 중요!!!!!!

## Series - Slicing

In [183]:
s

A    1000
B    2000
C    3000
dtype: int64

In [184]:
s2

0    1000
1    2000
2    3000
dtype: int64

### iloc slicing

In [185]:
s.iloc[0:2]

A    1000
B    2000
dtype: int64

### loc slicing

In [186]:
s.loc["A":"B"]

A    1000
B    2000
dtype: int64

In [187]:
# loc는 레이블 범위 만큼 딱 슬라잇이 됨

In [188]:
s2.iloc[0:2]

0    1000
1    2000
dtype: int64

In [189]:
s2.loc[0:2]

0    1000
1    2000
2    3000
dtype: int64

## 시리즈 수정/추가/삭제

In [190]:
s

A    1000
B    2000
C    3000
dtype: int64

In [191]:
s.loc["A"]

np.int64(1000)

In [192]:
# 수정 (딕셔너리 키값 밸류값 수정과 비슷함)
s.loc["A"] = 500
s

A     500
B    2000
C    3000
dtype: int64

In [193]:
s.iloc[0] = 500
s

A     500
B    2000
C    3000
dtype: int64

In [195]:
s["A"] = 500
s

A     500
B    2000
C    3000
dtype: int64

In [196]:
# loc 쓰는 것을 제일 추천

## 시리즈 연산

In [197]:
leslie = pd.Series([10, 20, 30], index=['NAVER','APPLE','엔비디아'])
민규1 = pd.Series([10, 20, 30], index=['엔비디아', 'NAVER', 'APPLE'])

# 우리 가족이 보유하고 있는 주식의 숫자를 계산
leslie + 민규1

APPLE    50
NAVER    30
엔비디아     40
dtype: int64

In [198]:
# 연산이 됨

In [199]:
leslie

NAVER    10
APPLE    20
엔비디아     30
dtype: int64

In [200]:
민규1

엔비디아     10
NAVER    20
APPLE    30
dtype: int64

In [201]:
# 인덱스의 순서는 다르지만 알아서 잘 더해짐 ! 

In [202]:
leslie = pd.Series([10, 20, 30], index=['NAVER','APPLE','테슬라'])
민규1 = pd.Series([10, 20, 30], index=['엔비디아', 'NAVER', 'APPLE'])
leslie+민규1

APPLE    50.0
NAVER    30.0
엔비디아      NaN
테슬라       NaN
dtype: float64

In [203]:
# NaN : 뭔가 비어있는 값이 있다

In [204]:
# pandas 아니면 머 더할 떄 반복문 짜야하는데, pandas 내부적으로는 series, dataframe 쓰면서 그럴 필요 없음. 

In [208]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = pd.Series([42800, 42700, 42050, 42950, 43000], index=date)
low = pd.Series([42150, 42150, 41300, 42150, 42350] , index=date)

diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [209]:
# 이걸 반복문으로 짜려면 복잡하다.

#idx_max = 0 
#dd
#d
#d

In [210]:
diff.idxmax()

'6/4'

In [211]:
# 나온 값중에서 6/4이 차이가 제일 크다. 

In [212]:
diff.idxmin()

'6/2'

In [213]:
diff.idxmax(), diff[diff.idxmax()]

('6/4', np.int64(800))

In [215]:
diff.idxmin(), diff[diff.idxmin()]

('6/2', np.int64(550))

In [214]:
# 주어진 것 중에 특정 값을 뽑을 때 쓴다.